repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: Sorting import statements
      language: python
      types: [python]
      args:
        - "--profile=black"

- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
    - id: black
      name: Black Python code formatting
      language: python
      types: [python]
      args:
        - "--line-length=125"
